from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from runtime.build_context import RuntimeContext, build_context_markdown, normalize_mode
from tools.list_skills import list_skills


SYSTEM_FILES_ORDER = [
    "core_prompt.md",
    "tools.md",
    "rules.md",
    "file_protocol.md",
    "output_contract.md",
]


WORKSPACE_FILES_ORDER = [
    "MARKET.md",
]

STYLE_FILE = "STYLE.md"

MODE_FILES = {
    "scheduler": "modes/scheduler.md",
    "manual": "modes/manual.md",
    "trigger": "modes/trigger.md",
}


def read_markdown_file(path: Path) -> str:
    if not path.exists():
        return f"# Missing File\n\n文件不存在：{path.name}\n"
    return path.read_text(encoding="utf-8").strip()


def load_system_sections(system_dir: str | Path) -> Dict[str, str]:
    system_path = Path(system_dir)
    sections: Dict[str, str] = {}

    for filename in SYSTEM_FILES_ORDER:
        sections[filename] = read_markdown_file(system_path / filename)

    return sections


def load_mode_section(system_dir: str | Path, mode: str) -> str:
    mode = normalize_mode(mode)
    mode_file = MODE_FILES[mode]
    return read_markdown_file(Path(system_dir) / mode_file)


def load_workspace_sections(workspace_dir: str | Path) -> Dict[str, str]:
    workspace_path = Path(workspace_dir)
    sections: Dict[str, str] = {}

    for filename in WORKSPACE_FILES_ORDER:
        sections[filename] = read_markdown_file(workspace_path / filename)

    return sections


def load_style_section(workspace_dir: str | Path) -> str:
    """
    Load workspace/STYLE.md.

    STYLE.md is generated by runtime.investment_style from config/investment_style.json.
    If it does not exist, return an empty string instead of injecting a Missing File block,
    because investment style is optional.
    """
    style_path = Path(workspace_dir) / STYLE_FILE
    if not style_path.exists():
        return ""
    return style_path.read_text(encoding="utf-8").strip()


def build_skills_summary_markdown(skills_dir: str | Path) -> str:
    result = list_skills(skills_dir)

    if not result.get("success"):
        error = result.get("error", "未知错误")
        return f"# 当前可用 Skills 摘要\n\n读取失败：{error}\n"

    skills = result.get("skills", [])
    if not skills:
        return "# 当前可用 Skills 摘要\n\n当前没有发现可用 skill。\n"

    lines: List[str] = [
        "# 以下为可用 Skill 的摘要，Skill 为你提供实用技能，必须通过读取完整的 SKILL.md 文件才能使用",
        "",
        "Skill 的目录为 `skills/`。当决定使用某个 skill 时，必须进入该 skill 目录并读取 `SKILL.md`。",
        "",
    ]

    for idx, skill in enumerate(skills, start=1):
        name = skill.get("name", "unknown")
        description = skill.get("description", "无描述")
        lines.append(f"## {idx}. {name}")
        lines.append(f"- description: {description}")
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def build_mode_task_block(
    mode: str,
    user_task: str = "",
    trigger_event: Dict[str, Any] | None = None,
) -> str:
    mode = normalize_mode(mode)

    lines: List[str] = [
        "# 当前调用信息",
        "",
        f"- mode: `{mode}`",
    ]

    if mode == "manual":
        lines.extend([
            "",
            "## 用户任务",
            "",
            user_task.strip() if user_task.strip() else "本轮未提供明确用户任务。请基于当前上下文进行安全的最小处理。",
        ])

    elif mode == "trigger":
        lines.extend([
            "",
            "## trigger_event",
            "",
        ])

        if trigger_event:
            lines.append("```json")
            lines.append(json.dumps(trigger_event, ensure_ascii=False, indent=2))
            lines.append("```")
        else:
            lines.append("本轮未提供 trigger_event。不得执行交易动作，只能说明缺失并记录。")

    else:
        lines.extend([
            "",
            "## 调度任务",
            "",
            "本轮为系统定时调用。请根据当前市场阶段、workspace 状态和最近记录，自主判断本轮动作。",
        ])

    return "\n".join(lines).strip() + "\n"


def build_agent_entry_block(
    mode: str = "scheduler",
    extra_instructions: str = "",
    user_task: str = "",
    trigger_event: Dict[str, Any] | None = None,
) -> str:
    mode = normalize_mode(mode)

    mode_desc = {
        "scheduler": "系统定时调用",
        "manual": "人工自然语言调用",
        "trigger": "事件触发调用",
    }[mode]

    lines: List[str] = [
        "# Agent 执行指令",
        "",
        f"你正在执行一次 `{mode}` 调用，即：{mode_desc}。",
        "",
        "请基于当前调用模式、system 规则、投资风格、workspace 信息、skills 摘要与动态上下文，完成本轮判断与更新。",
        "",
        "必须严格遵守 `output_contract.md` 中定义的 JSON 输出协议。",
        "",
        "## 执行边界",
        "",
    ]

    if mode == "scheduler":
        lines.extend([
            "- 遵守当前调用模式 prompt",
            "- 不执行与本轮任务无关的动作",
        ])
    elif mode == "manual":
        lines.extend([
            "- 用户任务是本轮最高优先级。",
            "- 不默认执行完整自动巡检。",
            "- 不默认读取 phase prompt。",
            "- 只读取完成用户任务所需的文件和工具。",
        ])
    else:
        lines.extend([
            "- trigger_event 是本轮最高优先级。",
            "- 只处理触发事件相关对象。",
            "- 不进行无关市场扫描。",
            "- 涉及交易前必须重新核验行情、账户、持仓、策略和风控。",
        ])

    lines.extend([
        "",
        "## 输出限制",
        "",
        "- 只能输出 `thinking`、`tool_call` 或 `final` 三种 JSON。",
        "- 不要输出 JSON 以外的普通文本及任何解释性文字。",
        "- 不要输出多个 JSON。",
        "- 不要解释系统设计。",
        "- 不要输出与本轮任务无关的内容。",
        "- 禁止输出多个 Markdown 代码块。",
    ])

    lines.extend([
        "",
        "---",
        "",
        build_mode_task_block(
            mode=mode,
            user_task=user_task,
            trigger_event=trigger_event,
        ),
    ])

    if extra_instructions.strip():
        lines.extend([
            "",
            "---",
            "",
            "# 附加指令",
            "",
            extra_instructions.strip(),
        ])

    return "\n".join(lines).strip() + "\n"


def render_system_prompt(
    system_dir: str | Path,
    workspace_dir: str | Path,
    context: RuntimeContext,
    extra_instructions: str = "",
    skills_dir: str | Path | None = None,
    mode: str | None = None,
    user_task: str | None = None,
    trigger_event: Dict[str, Any] | None = None,
    include_workspace: bool = True,
    include_style: bool = True,
    include_skills: bool = True,
) -> str:
    """
    渲染最终 system prompt。

    加载策略：
    1. 始终加载通用 system prompt。
    2. 只加载一个当前调用模式对应的 prompt：scheduler / manual / trigger。
    3. 可选加载 STYLE.md，作为投资风格约束。
    4. 可选加载 workspace 背景信息和 skills 摘要。
    5. 加载当前调用模式相关的入口指令和动态上下文。

    说明：
    - STYLE.md 由 runtime.investment_style 根据 config/investment_style.json 生成。
    """
    context_dict = context.to_dict()

    final_mode = normalize_mode(mode or context_dict.get("mode"))
    final_user_task = user_task if user_task is not None else context_dict.get("user_task", "")
    final_trigger_event = trigger_event if trigger_event is not None else context_dict.get("trigger_event", {})

    system_sections = load_system_sections(system_dir)
    mode_section = load_mode_section(system_dir, final_mode)
    style_section = load_style_section(workspace_dir) if include_style else ""
    dynamic_context = build_context_markdown(context)

    prompt_parts: List[str] = []

    # 1. 加载通用 system prompt
    for filename in SYSTEM_FILES_ORDER:
        prompt_parts.append(system_sections[filename])

    # 2. 加载当前调用模式 prompt
    prompt_parts.append(mode_section)

    # 3. 加载投资风格约束
    if style_section.strip():
        prompt_parts.append(style_section)

    # 4. 加载 workspace 背景信息
    if include_workspace:
        workspace_sections = load_workspace_sections(workspace_dir)
        for filename in WORKSPACE_FILES_ORDER:
            prompt_parts.append(workspace_sections[filename])

    # 5. 加载 skills 摘要
    if include_skills and skills_dir is not None:
        prompt_parts.append(build_skills_summary_markdown(skills_dir))

    # 6. 加载 Agent 入口执行指令
    prompt_parts.append(
        build_agent_entry_block(
            mode=final_mode,
            extra_instructions=extra_instructions,
            user_task=final_user_task,
            trigger_event=final_trigger_event,
        )
    )

    # 7. 加载动态运行上下文
    prompt_parts.append(dynamic_context)

    return "\n\n---\n\n".join(prompt_parts).strip() + "\n"


if __name__ == "__main__":
    from runtime.build_context import build_context

    project_root = Path(__file__).resolve().parents[1]
    system_dir = project_root / "system"
    workspace_dir = project_root / "workspace"
    skills_dir = project_root / "workspace" / "skills"

    ctx = build_context(
        workspace_dir,
        mode="scheduler",
        trigger_reason="manual_run",
    )

    final_prompt = render_system_prompt(
        system_dir=system_dir,
        workspace_dir=workspace_dir,
        context=ctx,
        skills_dir=skills_dir,
        mode="scheduler",
        extra_instructions="本轮请优先检查当前市场阶段、持仓、策略和未完成事项，并给出下一步动作建议。",
    )

    print(final_prompt)
